# Generated by Django 2.2.7 on 2019-12-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("companies", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="company", name="index", field=models.IntegerField(unique=True)
        )
    ]
